export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_LESSONS = 'GET_COURSE_LESSONS';
export const GET_LESSON = 'GET_LESSON';
export const POST_COURSE = 'POST_COURSE';
export const POST_LESSON = 'POST_LESSON';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_LESSON = 'DELETE_LESSON';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_LESSON = 'UPDATE_LESSON';
export const SET_LOADING = 'SET_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const USER_IS_ADMIN = 'USER_IS_ADMIN';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_BASKET = 'UPDATE_BASKET';
export const DELETE_BASKET = 'DELETE_BASKET';
export const GET_BASKET = 'GET_BASKET'
export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET';
export const REMOVE_ITEM_FROM_BASKET = 'REMOVE_ITEM_FROM_BASKET';



